### ISSUE TITLE
A problem about training time of model

### ISSUE THREAD

**Issue by zh57398** [alvinchangw/COCON_ICLR2021#2]
Hello, first of all, thank you very much for your training model, but I want to experience the process of my own training model, but the computer prompts me that it will take me a few years to train, which sounds ridiculous, but it's true. I want to ask you how long the training model has been used, and do you use GPU to train? And I have reduced the data set, but it has no effect. The training time has not been greatly reduced, or it will take several years. So I think the training time may not have much to do with the size of the data set, so what should affect the training time? It's very presumptuous to disturb you because of such a simple question, but I really need your help. Thank you very much and look forward to your reply.

**Comment by GaryYufei** [comment]
Hi,

Have you tried to run its inference result using the provided checkpoint? It is fast, but the generated output is very bad. Have you experienced a similar thing?

**Comment by alvinchangw** [comment]
Thank you for your interest in this work. As with most deep learning experiments, we conducted the training and evaluation of COCON on GPUs (~less than a week on a single NVIDIA RTX2080ti for training).

**Comment by zh57398** [comment]
> 你好，
> 
> 您是否尝试使用提供的检查点运行其推理结果？它很快，但生成的输出非常糟糕。你有没有经历过类似的事情？



> Hi,
> 
> Have you tried to run its inference result using the provided checkpoint? It is fast, but the generated output is very bad. Have you experienced a similar thing?

I'm very sorry to see your reply for such a long time. I haven't tried this method. I'm still in the learning stage. I just see from the code that I can start training from checkpoint.
